Update user stories, target user profile and value proposition
AY2021S2-CS2103T-W10-2/tp pull request #40
Opened 2021-02-26 04:41 UTC by github-amanda

Close #36

2021-02-26 05:01 UTC, kumsssss requested changes
just a minor change. other than that, LGTM.

2021-02-26 05:01 UTC, kumsssss commented on docs/DeveloperGuide.md
>  * has a need to manage a significant number of contacts
could change contacts to household items

2021-02-27 14:33 UTC, github-amanda commented on docs/DeveloperGuide.md
>  * has a need to manage a significant number of contacts
ok

2021-02-27 15:26 UTC, kumsssss approved these changes
LGTM

2021-02-27 15:26 UTC, merged